version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx_cont
    ports:
      - "80:80"
    networks:
      - notes-app
    restart: always
    depends_on:
      - django

  db:
    image: mysql:8.0
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notes-app
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  django:
    build:
      context: .
    container_name: django_cont
    command: >
      sh -c "python manage.py migrate --no-input &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - notes-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python manage.py check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


volumes:
  mysql-data:


networks:
  notes-app:
    driver: bridge
