name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout (not strictly needed, but good practice)
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Deploy on EC2
      - name: SSH into EC2 and deploy
        run: |
          ssh -i ~/.ssh/ec2_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            # If repo exists, update it; otherwise clone fresh
            if [ -d "django-notes-app" ]; then
              cd django-notes-app
              git pull
            else
              git clone https://github.com/rummannaqvi/django-notes-app.git
              cd django-notes-app
            fi
            # Stop old containers
            docker compose down || true
            # Build and start containers
            docker compose build
            docker compose up -d
          EOF

